# Generated by Django 4.1.4 on 2023-02-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Rubles'), ('USD', 'Dollars'), ('EUR', 'Euro')], default='RUB', max_length=3),
        ),
    ]
