# Generated by Django 4.1.4 on 2023-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_director_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='acters',
            field=models.ManyToManyField(to='movie_app.acter'),
        ),
    ]
